# Радиус проверки блоков вокруг игрока
radius: 10

# Блоки, возле которых нельзя ставить трапки
restricted-blocks:
  - BEDROCK
  - ENDER_CHEST
  - OBSIDIAN
  - CHEST

# Сообщение об ошибке
message: "&6&lVioTrap &8» &cВы находитесь слишком близко к защищенному объекту!"